CREATE TABLE client (
  id bigint generated by default as identity,
  name varchar(255),
  email varchar(255),
  PRIMARY KEY (id));

CREATE TABLE product (
  id bigint generated by default as identity,
  name varchar(255),
  PRIMARY KEY (id),
  UNIQUE KEY product_id_uindex (id)
);

CREATE TABLE basket (
  id bigint generated by default as identity,
  product_id bigint(20),
  client_id bigint(20),
  PRIMARY KEY (id),
  UNIQUE KEY basket_id_uindex (id),
  CONSTRAINT client_id FOREIGN KEY (client_id) REFERENCES client (id),
  CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES product (id)
)
